### PR TITLE
Use compiled ruby on windows with latest openssl

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
@mmzyk @jmink http://manhattan.ci.chef.co/view/Push%20Jobs%20Client/job/push-jobs-client-build/31/ passed successfully!

**Comment by ksubrama** [comment]
@manderson26 Can you double check this as well?

**Comment by tylercloke** [comment]
:+1: Looks good! Definitely double-check with @manderson26 though.

**Comment by manderson26** [comment]
Generally looks good; If you haven't already sure that it actually starts and runs on windows; I have some concern around that lib dir change causing it to not find stuff.

**Comment by ksubrama** [comment]
@manderson26 zmq_lib_dir is an unused variable that was last used many months ago :)  It just got killed in a refactor.

**Pull request merged**
