### PR TITLE
Chef::REST optimizations

### PR DESCRIPTION
**Pull request by patrick-wright**
Replaced Chef::REST with Chef::ServerAPI in pushy_client
Prefer Chef::HTTP::SimpleJSON over Chef::REST in windows_service
Use get instead get_rest in pushy_client

### CODE REVIEW

**Comment by manderson26** [comment]
👍

**Comment by scottopherson** [comment]
:+1:

**Comment by patrick-wright** [comment]
@thommay could you review please?

**Comment by mengesb** [comment]
When will this be present then in client rpms?

**Comment by thommay** [comment]
Looks great.

**Comment by btm** [comment]
Looks like this is in v2.1.0+

**Pull request merged**
